// <auto-generated />
using System;
using CodieGo_Adventure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CodieGo_Adventure.Migrations
{
    [DbContext(typeof(CGADbContext))]
    partial class CGADbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("CodieGo_Adventure.Models.AchievementBadge", b =>
                {
                    b.Property<int>("AchievementCompositeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("AchievementCompositeId"));

                    b.Property<int>("AchievementBadgeId")
                        .HasColumnType("int");

                    b.Property<int>("BadgeId")
                        .HasColumnType("int");

                    b.Property<string>("BadgeName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("AchievementCompositeId");

                    b.HasIndex("AchievementBadgeId");

                    b.ToTable("AchievementBadges");
                });

            modelBuilder.Entity("CodieGo_Adventure.Models.Challenges", b =>
                {
                    b.Property<int>("ChallengeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ChallengeId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<float>("TimeLimit")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TotalChallenge")
                        .HasColumnType("int");

                    b.HasKey("ChallengeId");

                    b.ToTable("Challenges");
                });

            modelBuilder.Entity("CodieGo_Adventure.Models.ChallengesProgress", b =>
                {
                    b.Property<int>("CProgressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CProgressId"));

                    b.Property<int>("AccumulatedPoints")
                        .HasColumnType("int");

                    b.Property<int>("AssessmentScores")
                        .HasColumnType("int");

                    b.Property<int>("ChallengeId")
                        .HasColumnType("int");

                    b.Property<int>("CompletedChallenge")
                        .HasColumnType("int");

                    b.Property<bool>("IsDaily")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastDailyReset")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ProfileId")
                        .HasColumnType("int");

                    b.Property<int>("SavedAssessmentScores")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<float>("Time")
                        .HasColumnType("float");

                    b.HasKey("CProgressId");

                    b.HasIndex("ChallengeId");

                    b.HasIndex("ProfileId");

                    b.ToTable("ChallengesProgress");
                });

            modelBuilder.Entity("CodieGo_Adventure.Models.History", b =>
                {
                    b.Property<int>("HistoryCompositeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("HistoryCompositeId"));

                    b.Property<int>("DailyPoints")
                        .HasColumnType("int");

                    b.Property<int>("HistoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("logDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("HistoryCompositeId");

                    b.HasIndex("HistoryId");

                    b.ToTable("History");
                });

            modelBuilder.Entity("CodieGo_Adventure.Models.Leaderboard", b =>
                {
                    b.Property<int>("LeaderboardId")
                        .HasColumnType("int");

                    b.Property<float>("BestTime")
                        .HasColumnType("float");

                    b.Property<int>("TotalPoints")
                        .HasColumnType("int");

                    b.HasKey("LeaderboardId");

                    b.ToTable("Leaderboard");
                });

            modelBuilder.Entity("CodieGo_Adventure.Models.LoginRecords", b =>
                {
                    b.Property<int>("RecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("RecordId"));

                    b.Property<DateTime>("LoginDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("SessionId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("RecordId");

                    b.HasIndex("UserId");

                    b.ToTable("LoginRecords");
                });

            modelBuilder.Entity("CodieGo_Adventure.Models.Modules", b =>
                {
                    b.Property<int>("ModuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ModuleId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TotalLessons")
                        .HasColumnType("int");

                    b.HasKey("ModuleId");

                    b.ToTable("Modules");
                });

            modelBuilder.Entity("CodieGo_Adventure.Models.ModulesProgress", b =>
                {
                    b.Property<int>("MProgressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MProgressId"));

                    b.Property<int>("CompletedLessons")
                        .HasColumnType("int");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("ModuleId")
                        .HasColumnType("int");

                    b.Property<int>("ProfileId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("MProgressId");

                    b.HasIndex("ModuleId");

                    b.HasIndex("ProfileId");

                    b.ToTable("ModulesProgress");
                });

            modelBuilder.Entity("CodieGo_Adventure.Models.PasswordResetTokens", b =>
                {
                    b.Property<int>("PasswordResetTokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PasswordResetTokenId"));

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UsedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("PasswordResetTokenId");

                    b.HasIndex("UserId");

                    b.ToTable("PasswordResetTokens");
                });

            modelBuilder.Entity("CodieGo_Adventure.Models.Profiles", b =>
                {
                    b.Property<int>("ProfileId")
                        .HasColumnType("int");

                    b.Property<string>("Bio")
                        .HasColumnType("longtext");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<byte[]>("Image")
                        .HasColumnType("longblob");

                    b.Property<string>("ImageExtension")
                        .HasColumnType("longtext");

                    b.Property<string>("ImageName")
                        .HasColumnType("longtext");

                    b.HasKey("ProfileId");

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("CodieGo_Adventure.Models.Puzzles", b =>
                {
                    b.Property<int>("PuzzleId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PuzzleName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("PuzzleId");

                    b.ToTable("Puzzles");
                });

            modelBuilder.Entity("CodieGo_Adventure.Models.Users", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("DateRegistered")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsNewUser")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CodieGo_Adventure.Models.AchievementBadge", b =>
                {
                    b.HasOne("CodieGo_Adventure.Models.ChallengesProgress", "ChallengesProgress")
                        .WithMany()
                        .HasForeignKey("AchievementBadgeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChallengesProgress");
                });

            modelBuilder.Entity("CodieGo_Adventure.Models.ChallengesProgress", b =>
                {
                    b.HasOne("CodieGo_Adventure.Models.Challenges", "Challenges")
                        .WithMany()
                        .HasForeignKey("ChallengeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CodieGo_Adventure.Models.Profiles", "Profiles")
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Challenges");

                    b.Navigation("Profiles");
                });

            modelBuilder.Entity("CodieGo_Adventure.Models.History", b =>
                {
                    b.HasOne("CodieGo_Adventure.Models.ChallengesProgress", "ChallengesProgress")
                        .WithMany()
                        .HasForeignKey("HistoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChallengesProgress");
                });

            modelBuilder.Entity("CodieGo_Adventure.Models.Leaderboard", b =>
                {
                    b.HasOne("CodieGo_Adventure.Models.ChallengesProgress", "ChallengesProgress")
                        .WithMany()
                        .HasForeignKey("LeaderboardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChallengesProgress");
                });

            modelBuilder.Entity("CodieGo_Adventure.Models.LoginRecords", b =>
                {
                    b.HasOne("CodieGo_Adventure.Models.Users", "Users")
                        .WithMany("LoginRecords")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Users");
                });

            modelBuilder.Entity("CodieGo_Adventure.Models.ModulesProgress", b =>
                {
                    b.HasOne("CodieGo_Adventure.Models.Modules", "Modules")
                        .WithMany()
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CodieGo_Adventure.Models.Profiles", "Profiles")
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Modules");

                    b.Navigation("Profiles");
                });

            modelBuilder.Entity("CodieGo_Adventure.Models.PasswordResetTokens", b =>
                {
                    b.HasOne("CodieGo_Adventure.Models.Users", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CodieGo_Adventure.Models.Profiles", b =>
                {
                    b.HasOne("CodieGo_Adventure.Models.Users", "Users")
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Users");
                });

            modelBuilder.Entity("CodieGo_Adventure.Models.Puzzles", b =>
                {
                    b.HasOne("CodieGo_Adventure.Models.ModulesProgress", "ModulesProgress")
                        .WithMany()
                        .HasForeignKey("PuzzleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ModulesProgress");
                });

            modelBuilder.Entity("CodieGo_Adventure.Models.Users", b =>
                {
                    b.Navigation("LoginRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
